#!/usr/bin/env bash
# update.sh — Update Godot domain knowledge (repomix + re-index)
#
# Usage:
#   ./domains/godot/scripts/update.sh              # regenerate all sources + rebuild index
#   ./domains/godot/scripts/update.sh --no-index   # only regenerate sources (skip embedding)
#
# Requirements:
#   - repomix (brew install repomix)
#   - python3 with chromadb, sentence-transformers (pip install -r requirements.txt)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
DOMAIN_DIR="${REPO_ROOT}/domains/godot"
SOURCES_DIR="${DOMAIN_DIR}/sources"
SKILLS_DIR="${REPO_ROOT}/.agents/skills/godot/references"
BUILD_DIR="/tmp/godot-knowledge-build"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

REBUILD_INDEX=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-index) REBUILD_INDEX=false; shift ;;
        -h|--help)
            echo "Usage: $0 [--no-index]"
            echo "  --no-index  Skip ChromaDB index rebuild"
            exit 0
            ;;
        *) shift ;;
    esac
done

if ! command -v repomix &>/dev/null; then
    log_error "repomix not found. brew install repomix"
    exit 1
fi

mkdir -p "${BUILD_DIR}"

get_remote_commit() {
    local repo_url="$1"
    git ls-remote "${repo_url}.git" HEAD 2>/dev/null \
        | awk '{print substr($1,1,7)}' \
        | head -1
}

prepend_header() {
    local packed_file="$1"
    local repo_url="$2"
    local commit_hash="$3"

    if [ ! -f "$packed_file" ]; then return 1; fi

    local file_count token_count
    file_count=$(grep "Total Files:" "$packed_file" 2>/dev/null | awk '{print $3}' | head -1)
    token_count=$(grep "Total Tokens:" "$packed_file" 2>/dev/null | awk '{print $3}' | head -1)
    local now=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    local repomix_ver=$(repomix --version 2>/dev/null || echo "unknown")

    local tmpfile=$(mktemp)
    {
        echo "<!--"
        echo "  Generated by: domains/godot/scripts/update.sh"
        echo "  Generated at: $now"
        echo "  Source repo:  $repo_url"
        echo "  Commit:       $commit_hash"
        echo "  Repomix:      $repomix_ver"
        echo "  Files:        ${file_count:-unknown}"
        echo "  Tokens:       ${token_count:-unknown}"
        echo "-->"
        echo ""
    } > "$tmpfile"
    cat "$packed_file" >> "$tmpfile"
    mv "$tmpfile" "$packed_file"

    log_info "    Header: commit $commit_hash, ${file_count:-?} files, ${token_count:-?} tokens"
}

pack_one() {
    local name="$1" repo_url="$2" include_pat="$3" ignore_pat="$4"
    local out="${BUILD_DIR}/${name}-packed.md"

    log_info "  $name..."
    repomix --remote "${repo_url}" --style markdown \
        --include "${include_pat}" --ignore "${ignore_pat}" \
        -o "${out}" > /dev/null 2>&1

    if [ -f "${out}" ]; then
        local commit=$(get_remote_commit "${repo_url}")
        prepend_header "${out}" "${repo_url}" "${commit:-unknown}"

        # Copy to domain sources and skills references
        cp "${out}" "${SOURCES_DIR}/${name}-packed.md"
        mkdir -p "${SKILLS_DIR}"
        cp "${out}" "${SKILLS_DIR}/${name}-packed.md"

        local size=$(du -h "${out}" | cut -f1)
        log_info "    ✓ ${name} (${size})"
    else
        log_error "    ✗ ${name} FAILED"
        return 1
    fi
}

log_info "Updating Godot domain knowledge..."
log_info "  Sources: ${SOURCES_DIR}"
log_info "  Skills:  ${SKILLS_DIR}"

pack_one "godot-docs-reference" \
    "https://github.com/godotengine/godot-docs" \
    "classes/*.rst,getting_started/**/*.rst" \
    "**/*.png,**/*.jpg,**/*.gif,**/*.svg,**/_static/**,**/_extensions/**" || true

pack_one "godot-docs-3d" \
    "https://github.com/godotengine/godot-docs" \
    "tutorials/3d/**/*.rst" \
    "**/*.png,**/*.jpg,**/*.gif,**/*.svg" || true

pack_one "godot-demos" \
    "https://github.com/godotengine/godot-demo-projects" \
    "3d/**/*.gd,viewport/**/*.gd,2d/**/*.gd,gui/**/*.gd,audio/**" \
    "**/*.png,**/*.jpg,**/*.import,**/*.uid" || true

log_info "Sources updated."

if [ "$REBUILD_INDEX" = true ]; then
    log_info "Rebuilding ChromaDB index..."
    python3 "${REPO_ROOT}/scripts/embed_index.py" --domain godot
fi

echo ""
echo "Done. To commit:"
echo "  git add .agents/skills/godot/references/"
echo "  git commit -m 'chore(godot): update knowledge from upstream'"
